name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu Latest GCC",
            tag: gnu,
            cc: "gcc",
            cxx: "g++"
          }
          - {
            name: "Ubuntu Latest CLang",
            tag: "clang",
            cc: "clang",
            cxx: "clang++"
          }
  
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Get tags
      run: git fetch --tags origin
    
    - name: Install dependencies
      run: sudo apt install -y clang libboost-all-dev ninja-build qtbase5-dev libqt5svg5-dev python3-pip

    - name: Install conan
      run: sudo pip install conan

    - name: Install conan dependencies
      run: conan install . --output-folder=.conan/${{ matrix.config.cc }}/release --build=missing --profile=.conan/${{ matrix.config.cc }}/release/profile --profile:build=.conan/${{ matrix.config.cc }}/release/profile

    - name: Configure CMake
      run: cmake --preset="ci_${{ matrix.config.tag }}_release"

    - name: Build
      run: cmake --build ${{github.workspace}}/build
